name: Terraform CI

on: 
  pull_request:
    branches:
      - main

env:
  GO_VERSION: '1.19'
  TERRAFORM_VERSION: '1.3'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v3

    - name: run downloadclient
      run: docker run -d --name transmission linuxserver/transmission

    - name: config rights
      run: >
        sudo chown 1000:1000 ${{ github.workspace }}/.github/workflows/config.xml &&
        sudo chmod +x ${{ github.workspace }}/.github/workflows/test.sh

    - name: run provider
      run: >
        docker run -d
        -e PUID=1000
        -e PGID=1000
        --link transmission
        -v ${{ github.workspace }}/.github/workflows/test.sh:/scripts/test.sh
        -v ${{ github.workspace }}/.github/workflows/config.xml:/config/config.xml
        -p 8989:8989
        --health-cmd "curl --fail http://localhost:8989/system/status || exit 1"
        linuxserver/sonarr

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Run a Terraform init  
      run: terraform init

    - name: Run a Terraform validate    
      run: terraform validate

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Download dependencies
      run: go mod download
      working-directory: ${{ github.workspace }}/test

    - name: Test
      working-directory: ${{ github.workspace }}/test
      run: go test
      env:
        SONARR_URL: "http://localhost:8989"
        SONARR_API_KEY: "b01df9fca2e64e459d64a09888ce7451"